### PR TITLE
Json

### PR DESCRIPTION
**Pull request by gpolaert**
Changelog:
- Add a Json formatter to the library

### CODE REVIEW

**Comment by sandrokeil** [comment]
Cool, this solves #13 :+1: 

Can you fix the error `PHP Fatal error:  Cannot declare class ZendTest\Log\Formatter\XmlTest, because the name is already in use in /home/travis/build/zendframework/zend-log/test/Formatter/XmlTest.php on line 255` please. See Travis for more details.

**Comment by gpolaert** [comment]
I'm fixing build issue. I've just set my env.

**Comment by gpolaert** [comment]
Sorry for the incremental PR :)
@sandrokeil, is it okay now?

**Comment by luads** [comment]
+1

It would be useful for our Logentries integration.

**Comment by gpolaert** [comment]
@hisamu  :) Use Logmatic.io instead #troll-I-m-a-Logmatic-Evangelist ^^

**Comment by gpolaert** [comment]
@sandrokeil When do you plan a release? Are you depending of the Zend master release?

**Comment by sandrokeil** [comment]
@gpolaert Sorry, I'm not a maintainer.

**Comment by weierophinney** [comment]
Thanks, @gpolaert!

**Pull request merged**
