### PR TITLE
Allow ability to chmod new log files

### PR DESCRIPTION
**Pull request by amcsi**
I don't know how I could test this.

Anyway I've had several projects where for CLI and nginx I use the same ZF2 project's logger, however the two users are different and I didn't have access to the umask settings. So I think something like this would be helpful.

### CODE REVIEW

**Comment by awartoft** [comment]
Tests missing

**Comment by amcsi** [comment]
How do you test changes to the filesystem?

**Comment by awartoft** [comment]
Just generate a file either in `/tmp` or in the actually project and see if it's correctly generated, also don't forget to cleanup.

**Comment by weierophinney** [comment]
Use sys_get_temp_dir(); that ensures that write permissions are correct
regardless of where the package is installed or who the user is.

**Comment by weierophinney** [comment]
Wrote a unit test and merged to develop for release with 2.7.0.

**Comment by amcsi** [comment]
This probably won't work when using a virtual machine using NFS on an NTFS partition (with ntfs-3g). That is the reason I included the ErrorException bit in the first place, which @weierophinney seemed to remove.

**Comment by weierophinney** [comment]
If I removed it, it was due to:
- no tests covering the behavior
- no comments indicating why it was needed

Submit a new PR to re-introduce the behavior that includes one or more of
the above, and I'll re-review.

**Comment by amcsi** [comment]
Will it be enough to just emulate a `chmod()` function that just throws an ErrorException?

But also note that if I do, I would need to remove this bit of code of yours: https://github.com/zendframework/zend-log/pull/15/files#diff-e4491cecd23d8a25fa688df2314fd7dfR89

Yours is more strict, but I assert that it would not be possible to differentiate whether `chmod()` fails due to a true failure (who knows why), vs the chmod interface for a special type of filesystem might just be inherently weird and we need to go along with it.

**Pull request closed without merging**
