### PR TITLE
return inconsistency between interface and its implementation

### PR DESCRIPTION
**Pull request by gianarb**

### CODE REVIEW

**Comment by Maks3w** [comment]
This is incomplete. Clearly the method return array.

**Comment by gianarb** [comment]
The interface docs is wrong?

**Comment by gianarb** [comment]
I'm checked other filters and they return array.. I changed interface docs @Maks3w

**Comment by Maks3w** [comment]
I've reviewed this again and I see `Base`, `Db`, and `FirePHP` returns `array` but the rest of implementations returns `string`

We could either add both types to the return or try to fix the interface violation on those formatters which return array

**Comment by weierophinney** [comment]
IIRC, those formatters need to return an array so that the data can be
consumed by the relevant writers.

**Comment by weierophinney** [comment]
I'm going to merge, but change the return value annotation to be `string|array`. We introduced arrays when new writers introduced new use cases and concerns, and both are valid; however, you can only use specific formatters with specific writers due to the differences.

**Comment by weierophinney** [comment]
Merged to develop for release with 2.7.0

**Pull request closed without merging**
